In [1]:
import sys
sys.path.append(".")

from src.datos import mostrar_ticker, cargar_universo
from src.fundamentals import (
    estados_financieros, mostrar_estados,
    crecimiento_historico,
    ratios_avanzados, mostrar_ratios_completos,
    comparar_peers,
    fcf_historico,
    analisis_completo
)
from src.graficos import (
    graficar_revenue_eps,
    graficar_fcf_historico,
    graficar_margenes,
    heatmap_peers
)
import pandas as pd

universo = cargar_universo()
print("Modulos de fundamentals cargados")

Modulos de fundamentals cargados

In [2]:
mostrar_ratios_completos("MELI")

============================================================
  ANALISIS FUNDAMENTAL - MELI
============================================================

VALUACION
  PE (trailing):      41.01
  PE (forward):       24.28
  PEG:                1.01
  P/B:                10.81
  P/S:                2.48
  EV/EBITDA:          22.70
  EV/Revenue:         2.81
  Dividend Yield:     N/A

RENTABILIDAD
  ROE:                31.26%
  ROA:                5.11%
  Margen Bruto:       49.47%
  Margen Operativo:   6.91%
  Margen Neto:        6.04%

SOLVENCIA
  Debt/Equity:        169.98
  Current Ratio:      1.16
  Quick Ratio:        0.44

OTROS
  Beta:               1.41
  Payout Ratio:       0.00%

============================================================

In [3]:
mostrar_estados("MELI")

============================================================
  ESTADOS FINANCIEROS - MELI
============================================================

ESTADO DE RESULTADOS (P&L)
------------------------------------------------------------
                   2025   2024   2023   2022  2021
EBITDA             3.82   3.21   2.25   1.32   NaN
Basic EPS          0.00   0.00   0.00   0.00   NaN
Net Income         2.00   1.91   0.99   0.48   NaN
Operating Income   3.20   2.63   2.21   1.07   NaN
Gross Profit      12.86   9.58   7.59   5.20   NaN
Total Revenue     28.89  20.78  15.11  10.78   NaN
(valores en miles de millones USD)

BALANCE GENERAL
------------------------------------------------------------
                            2025   2024   2023   2022  2021
Total Debt                 11.39   6.85   5.33   5.41   NaN
Stockholders Equity         6.75   4.35   3.07   1.83   NaN
Long Term Debt              4.49   2.81   2.11   2.59   NaN
Total Assets               42.67  25.20  17.61  13.74   NaN
Current Assets             33.57  20.14  14.26  10.95   NaN
Cash And Cash Equivalents   3.67   2.64   2.56   1.91   NaN
(valores en miles de millones USD)

FLUJO DE EFECTIVO
------------------------------------------------------------
                              2025  2024  2023  2022  2021
Free Cash Flow               10.77  7.06  4.63  2.48   NaN
Repurchase Of Capital Stock  -0.00 -0.00 -0.36 -0.15   NaN
Capital Expenditure          -1.34 -0.86 -0.51 -0.46   NaN
Cash Dividends Paid            NaN   NaN   NaN  0.00   0.0
Operating Cash Flow          12.12  7.92  5.14  2.94   NaN
(valores en miles de millones USD)

In [4]:
crec = crecimiento_historico("MELI")
crec

{'ticker': 'MELI',
 'revenue_cagr_%': np.float64(38.91),
 'revenue_años': 3,
 'net_income_cagr_%': np.float64(60.61),
 'net_income_años': 3,
 'fcf_cagr_%': np.float64(63.06),
 'fcf_años': 3,
 'margen_neto_actual_%': np.float64(6.91),
 'margen_neto_inicio_%': np.float64(4.47),
 'expansion_margen_pp': np.float64(2.44)}

In [5]:
fcf = fcf_historico("MELI")
fcf

    año  FCF_USD_M  FCF_USD_B  variacion_%
0  2022       2485       2.48          NaN
1  2023       4631       4.63        86.69
2  2024       7058       7.06        52.48
3  2025      10773      10.77        52.55

In [6]:
graficar_revenue_eps("MELI")

In [7]:
graficar_margenes("MELI")

In [8]:
graficar_fcf_historico("MELI")

In [9]:
peers_energia_ar = ["YPF", "PAM", "TGS"]
df_peers = comparar_peers(peers_energia_ar)
df_peers

,Ticker,PE_trailing,PB,EV_EBITDA,ROE_%,Margen_Operativo_%,Margen_Neto_%,Debt_Equity,Dividend_Yield_%
0,YPF,NaN,1.541807,5.130,-3.256000,17.752,-2.141000,92.454,NaN
1,PAM,9.842423,1.149735,142.023,12.102999,19.372,20.306000,49.617,NaN
2,TGS,14.276191,2.009771,-0.210,14.340000,51.495,24.672002,43.851,323.0

In [10]:
heatmap_peers(peers_energia_ar)

In [11]:
peers_tech = ["MELI", "GLOB", "NU"]
df_tech = comparar_peers(peers_tech)
df_tech

,Ticker,PE_trailing,PB,EV_EBITDA,ROE_%,Margen_Operativo_%,Margen_Neto_%,Debt_Equity,Dividend_Yield_%
0,MELI,41.008717,10.813482,22.704,31.258,6.908000,6.037000,169.977,None
1,GLOB,16.131004,0.773451,5.172,4.956,19.084999,4.192000,24.230,None
2,NU,22.872883,5.804301,NaN,30.278,52.145000,41.035998,NaN,None

In [12]:
analisis_completo("MELI")

############################################################
#  ANALISIS COMPLETO - MELI
############################################################
=== MercadoLibre, Inc. (MELI) ===
Sector: Consumer Cyclical | Industria: Internet Retail
País: Uruguay | Moneda: USD
Precio actual: $1,553.00
Market Cap: $78.73B
Rango 52w: $1,552.63 - $2,645.22
PE: 41.01
PB: 10.81
ROE: 31.26%
Margen operativo: 6.91%
==================================================

============================================================
  ANALISIS FUNDAMENTAL - MELI
============================================================

VALUACION
  PE (trailing):      41.01
  PE (forward):       24.28
  PEG:                1.01
  P/B:                10.81
  P/S:                2.48
  EV/EBITDA:          22.70
  EV/Revenue:         2.81
  Dividend Yield:     N/A

RENTABILIDAD
  ROE:                31.26%
  ROA:                5.11%
  Margen Bruto:       49.47%
  Margen Operativo:   6.91%
  Margen Neto:        6.04%

SOLVENCIA
  Debt/Equity:        169.98
  Current Ratio:      1.16
  Quick Ratio:        0.44

OTROS
  Beta:               1.41
  Payout Ratio:       0.00%

============================================================


============================================================
  ESTADOS FINANCIEROS - MELI
============================================================

ESTADO DE RESULTADOS (P&L)
------------------------------------------------------------
                   2025   2024   2023   2022  2021
EBITDA             3.82   3.21   2.25   1.32   NaN
Basic EPS          0.00   0.00   0.00   0.00   NaN
Net Income         2.00   1.91   0.99   0.48   NaN
Operating Income   3.20   2.63   2.21   1.07   NaN
Gross Profit      12.86   9.58   7.59   5.20   NaN
Total Revenue     28.89  20.78  15.11  10.78   NaN
(valores en miles de millones USD)

BALANCE GENERAL
------------------------------------------------------------
                            2025   2024   2023   2022  2021
Total Debt                 11.39   6.85   5.33   5.41   NaN
Stockholders Equity         6.75   4.35   3.07   1.83   NaN
Long Term Debt              4.49   2.81   2.11   2.59   NaN
Total Assets               42.67  25.20  17.61  13.74   NaN
Current Assets             33.57  20.14  14.26  10.95   NaN
Cash And Cash Equivalents   3.67   2.64   2.56   1.91   NaN
(valores en miles de millones USD)

FLUJO DE EFECTIVO
------------------------------------------------------------
                              2025  2024  2023  2022  2021
Free Cash Flow               10.77  7.06  4.63  2.48   NaN
Repurchase Of Capital Stock  -0.00 -0.00 -0.36 -0.15   NaN
Capital Expenditure          -1.34 -0.86 -0.51 -0.46   NaN
Cash Dividends Paid            NaN   NaN   NaN  0.00   0.0
Operating Cash Flow          12.12  7.92  5.14  2.94   NaN
(valores en miles de millones USD)

CRECIMIENTO HISTORICO
------------------------------------------------------------
  revenue_cagr_%: 38.91
  revenue_años: 3
  net_income_cagr_%: 60.61
  net_income_años: 3
  fcf_cagr_%: 63.06
  fcf_años: 3
  margen_neto_actual_%: 6.91
  margen_neto_inicio_%: 4.47
  expansion_margen_pp: 2.44

FREE CASH FLOW HISTORICO
------------------------------------------------------------
 año  FCF_USD_M  FCF_USD_B  variacion_%
2022       2485       2.48          NaN
2023       4631       4.63        86.69
2024       7058       7.06        52.48
2025      10773      10.77        52.55

############################################################

In [13]:
mi_portfolio = universo["portfolios"]["personal"]
print("ANALISIS FUNDAMENTAL DE TU PORTFOLIO")
print("=" * 60)
df_mi_portfolio = comparar_peers(mi_portfolio)
df_mi_portfolio

ANALISIS FUNDAMENTAL DE TU PORTFOLIO
============================================================

,Ticker,PE_trailing,PB,EV_EBITDA,ROE_%,Margen_Operativo_%,Margen_Neto_%,Debt_Equity,Dividend_Yield_%
0,YPF,NaN,1.541807,5.130,-3.256000,17.752,-2.141000,92.454,NaN
1,PAM,9.842423,1.149735,142.023,12.102999,19.372,20.306000,49.617,NaN
2,TGS,14.276191,2.009771,-0.210,14.340000,51.495,24.672002,43.851,323.0
3,MELI,41.008717,10.813482,22.704,31.258000,6.908,6.037000,169.977,NaN

In [14]:
sector = universo["sectores"]["energia_ar"]
df_sector = comparar_peers(sector)
df_sector.style.background_gradient(cmap="RdYlGn", subset=["ROE_%", "Margen_Operativo_%"])